config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  get 'google_suburb_autocomplete' => 'site#google_suburb_autocomplete'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
  end

  def google_suburb_autocomplete

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MjRailsPlayground</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1><%= link_to "MJ's Rails Playground", root_path %></h1>

<%= yield %>

</body>
</html>

app/views/site/google_suburb_autocomplete.html.erb
<h1>Google Autocomplete</h1>
<%= label_tag :suburb, "Enter a Suburb: " %>
<%= text_field_tag :suburb, nil, id: 'js-google-autocomplete-suburb', style: 'width: 300px' %>

<script type="text/javascript">
$(function() {
    var input = document.getElementById('js-google-autocomplete-suburb');
    var options = {
      types: ['(cities)'],
      componentRestrictions: {country: 'au'}
    };
    autocomplete = new google.maps.places.Autocomplete(input, options);
});
</script>

app/views/site/index.html.erb
<ul>
    <li>
        <%= link_to 'Google Suburb Autocomplete', google_suburb_autocomplete_path %>
    </li>
</ul>